### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined when validate prop is missing

### ISSUE THREAD

**Issue by tomasikp** [scull7/bs-awesomize#4]
```
 TypeError: Cannot read property 'length' of undefined
     at Object.fromArray (/Users/piotrtomasik/Developer/influential/agent-alpha/node_modules/bs-platform/lib/js/belt_List.js:627:14)
     at /Users/piotrtomasik/Developer/influential/agent-alpha/node_modules/bs-awesomize/src/Awesomize.bs.js:208:51
     at Object._1 (/Users/piotrtomasik/Developer/influential/agent-alpha/node_modules/bs-platform/lib/js/curry.js:69:12)
     at Object.map (/Users/piotrtomasik/Developer/influential/agent-alpha/node_modules/bs-platform/lib/js/array.js:104:20)
     at inputConvert (/Users/piotrtomasik/Developer/influential/agent-alpha/node_modules/bs-awesomize/src/Awesomize.bs.js:194:18)
     at Object.fromJs (/Users/piotrtomasik/Developer/influential/agent-alpha/node_modules/bs-awesomize/src/Awesomize.bs.js:263:17)
     at Object.compile (/Users/piotrtomasik/Developer/influential/agent-alpha/node_modules/bs-awesomize/index.js:30:36)
     at Object.compile (/Users/piotrtomasik/Developer/influential/agent-alpha/src/awesome2/index.js:15:31)
     at EditProfile (/Users/piotrtomasik/Developer/influential/agent-alpha/src/user/index.js:298:38)
     at resolveFieldValueOrError (/Users/piotrtomasik/Developer/influential/agent-alpha/node_modules/graphql/execution/execute.js:544:18)
     at resolveField (/Users/piotrtomasik/Developer/influential/agent-alpha/node_modules/graphql/execution/execute.js:508:16)
     at /Users/piotrtomasik/Developer/influential/agent-alpha/node_modules/graphql/execution/execute.js:330:20
     at process._tickCallback (internal/process/next_tick.js:178:7)
```

```
title: {
        read: ({title}) => title,

        sanitize: (val) => {
          if (R.is(String, val)) {
            return R.trim(val)
          }
          return val
        },
      },
```

**Comment by tomasikp** [comment]
@scull7 should prob return a better error message

**Comment by scull7** [comment]
Released with: https://github.com/scull7/bs-awesomize/commit/1c426f9df7ffc1cdfc6fd3ce306ac83a0d85ed76
